### ISSUE TITLE
How do I use CMB2 Metatabs Options in the post type: page and post?

### ISSUE THREAD

**Issue by jquimera** [rogerlos/cmb2-metatabs-options#10]
Hi, can I use CMB2 MetaTabs in the post type: page and post? like this: ![Image of Yaktocat](https://cloud.githubusercontent.com/assets/4693056/6799661/1fbbd440-d1ee-11e4-969e-f98ffcf54a57.jpg)

**Comment by rogerlos** [comment]
If you're asking what I think you're asking, you would set `['topmenu'] = 'edit.php'` and `['postslug'] = 'page'` when calling the class. This, in theory, would add an options page to the "page" menu in admin.

If you're asking about adding a box to the actual post or page editor, that's what CMB2 does out of the box...?

**Comment by jquimera** [comment]
@rogerlos Thanks for answering me. I'm from Brazil and my english is horrible, forgive me. No, I do not want "theme opions" I just want to organize my metaboxes in Tabs. You can do this with your plugin? Thank you.

**Comment by rogerlos** [comment]
Yes, if they're all on the same options page. By default, they are put into the default WordPress admin style. CMO adds a tiny bit of styling, which you can remove by setting `['admincss']` to false or, if you want to overwrite the WordPress styles, you could send properly formatted CSS which would be added to the page. 

CMO uses the "standard" WordPress tab html (some data attributes left out):

``` html
<h2 class="nav-tab-wrapper">
    <a href="#" id="opt-tab-foobar" class="nav-tab opt-tab">
        The Tab Title
    </a>
    <!-- more tabs ... -->
</h2>
<div class="opt-content" id="opt-content-foobar">
    <div class="meta-box-sortables ui-sortable">
        <!-- metaboxes for first tab end up here -->
    </div>
</div>
<!-- more opt-content boxes to match number of tabs -->
```

So if you're looking to mimic your example with the side tabs, you'd need to override the standard WP styles, but structurally it's doable.

**Comment by rogerlos** [comment]
To be clear, you would send your CSS in the class args:

``` php
$args['admincss'] = '.nav-tab-wrapper { position: absolute !important; }';
$args['admincss'] .= '.opt-content { background: red; }';
```

Etc, however you wanted to do it. Looking at my code, if you send CSS I still add my cleanup CSS. In the next version I'll hopefully make this a bit more flexible.

**Comment by jquimera** [comment]
@rogerlos Right, i appreciate it. This will be of great help to customize the options panel. But I would like to add something. Maybe I expressed myself badly. I apologize, I do not want to abuse. But what I want is to use your plugin on page / post. I want to put my custom fields for posts and pages within the tabs.

**Comment by jquimera** [comment]
@rogerlos I do not want to use the theme options for now, I just put my metaboxes within tabs in post_type.

**Comment by jquimera** [comment]
@rogerlos So ... it is possible to use the plugin like that? Thanks.

**Comment by rogerlos** [comment]
@jquimera, this plugin is here only to added CMB2 boxes to stand-alone options pages. CMB2 can already add boxes to existing pages.
