### ISSUE TITLE
Add Metaboxes to Post and Pages post types

### ISSUE THREAD

**Issue by ivorpad** [rogerlos/cmb2-metatabs-options#11]
No the same issue from https://github.com/rogerlos/cmb2-metatabs-options/issues/10

I'm trying to add the metatabs-options to the Post and Page post types and I'm unable to do so. I tried with the `$show_on` variable and I'm afraid this is not the way to do it. 

```
'topmenu'    => 'edit.php',
'postslug'   => 'page',
```

With CMB2 I can accomplish this by setting `object_type` to `object_type => array('post', 'page')` but I couldn't set it up in your plugin. I would appreciate your help.

<img width="731" alt="screen shot 2016-10-06 at 19 23 30" src="https://cloud.githubusercontent.com/assets/52452/19174100/66016f2e-8bfa-11e6-9b4a-c47b44d9c94a.png">

Thanks for releasing this, amazing stuff.

**Comment by rogerlos** [comment]
This plugin does not add boxes to existing pages, that is what CMB2 does. This plugin gathers boxes and displays them in a separate options page.

If you're looking to add a box to both an existing page via CMB2 and then show the box again in an options page, you would need to define your own show_on filter.

https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters

CMO is looking for the show_on value to be 'options-page', so your filter would need to return that value for your options page context and the normal value in other contexts.
