### ISSUE TITLE
How will i show it under page and post? 

### ISSUE THREAD

**Issue by websumon** [rogerlos/cmb2-metatabs-options#12]
I have already used it, but it did not work
`'topmenu'    => 'post-new.php',
'postslug'   => 'page',`

I would like to see all options here
![firefox_screenshot_2016-10-22t13-47-23 311z](https://cloud.githubusercontent.com/assets/8939556/19619870/0b6599c4-9892-11e6-8b3d-b489ee4a6595.png)

**Comment by Jackyowen** [comment]
Me too, pls

**Comment by rogerlos** [comment]
This is actually a CMB2 metabox configuration issue, I believe. When defining your boxes:

```php
$my_box = [
    ...
    'object_types' => [
        'page',
    ],
    ...
]
```

It's not clear to me at a glance what the default value is, possibly `[ 'post' ]` .

**Comment by rogerlos** [comment]
And to be clear, now that I see this, all this plugin does is gather metaboxes into separate options pages, not add them to existing pages.
