### ISSUE TITLE
How to add a capability ??

### ISSUE THREAD

**Issue by Julianoe** [rogerlos/cmb2-metatabs-options#13]
Could you tell me how you would add a capability to view the link in the admin menu AND edit the settings page created with this class ?

**Comment by rogerlos** [comment]
Version 1.2 adds a new parameter which can be set to have the plugin check the user's capability before displaying them the page, and the plugin now checks by default that the user's capability matches the menu capability.

**Comment by Julianoe** [comment]
Sorry for reopening but i used the capability and view_capability args and my user is still unauthorized and the admin for this user does not appear either...
Here are my args 

```
$args = array(
		'key'      => $options_key,
		'title'    => __('Wine presentation options', 'tstopdf'),
		'topmenu'  => '',
		'cols'     => 2,
		'boxes'    => cmb2_metatabs_options_add_boxes( $options_key ),
		'tabs'     => cmb2_metatabs_options_add_tabs(),
		'menuargs' => array(
			'menu_title' => __('Wine presentation options', 'tstopdf'),
		),
		'capability' => 'manage_tstopdf_presentation_options',
		'view_capability' => 'manage_tstopdf_presentation_options'
	);
```
