### ISSUE TITLE
I'm getting a fatal error on line 282 

### ISSUE THREAD

**Issue by noelmcg** [rogerlos/cmb2-metatabs-options#14]
Hi I'm getting the following error? 

**Fatal error: Using $this when not in object context in ....../wp-content/plugins/hpw-functionality/cmb2-metatabs-options/code/cmb2_metatabs_options.php on line 282**

Have tried using the example code instead of my own and I still get the error.

Everything works fine in my single install development environment. When I move the working code to a multisite environment I get this error?

**Comment by rogerlos** [comment]
What version of PHP are you using? In theory > 5.4 should allow this within anonymous functions. Is your multisite install on the same server?

**Comment by rogerlos** [comment]
Closing as not enough info, re-open if you can provide some data on your server.
