### ISSUE TITLE
[FEATURE] [CODE-SAMPLE] Function to get values by ID-key easily

### ISSUE THREAD

**Issue by Kaleidosko** [rogerlos/cmb2-metatabs-options#15]
Hello everyone,

I've found this function in an other settings-page snippet and I like it very much. Maybe the author want to integrate it into the code.

Now you could get any key with the following line:
`echo settingspage_get_option('ID-OF-YOUR-FIELD'):`
easy, isn't it?

Source:
https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages

Greetings

```
/* Get value for option-page key */
function settingspage_get_option( $key = '', $default = null ) {

	$options_key = 'settingspage_options';

	if ( function_exists( 'cmb2_get_option' ) ) {
		// Use cmb2_get_option as it passes through some key filters.
		return cmb2_get_option( $options_key, $key, $default );
	}

	// Fallback to get_option if CMB2 is not loaded yet.
	$opts = get_option( $options_key, $key, $default );

	$val = $default;

	if ( 'all' == $key ) {
		$val = $opts;
	} elseif ( array_key_exists( $key, $opts ) && false !== $opts[ $key ] ) {
		$val = $opts[ $key ];
	}

	return $val;
}
```

**Comment by rogerlos** [comment]
This looks to be a nice bit of code, but this plugin is designed to help on the back end, and probably has enough "scope creep" already. But thank you!
