### ISSUE TITLE
Activating the page for a specific user role

### ISSUE THREAD

**Issue by Julianoe** [rogerlos/cmb2-metatabs-options#17]
Hi !
I'm glad you updated after my comments :)
I have a last difficulty though, probably a simple problem not linked to the code you wrote: i'm trying to make the option page (created following your example) accessible to a user which for i created a specific role. This user role does not have access to the optons-general.php page. 

What should i provide as 'topmenu' arg then? How can i create an admin menu item dedicated to this option page ?

Thanks a lot in advance for the help ;)

**Comment by rogerlos** [comment]
See this in the wiki: https://github.com/rogerlos/cmb2-metatabs-options/wiki/Arguments#topmenu

Just leave `topmenu` empty (`''`), and your page will be added as a new top-level page.
