### ISSUE TITLE
Make it easier to edit icon, position and capability

### ISSUE THREAD

**Issue by ajuliano** [rogerlos/cmb2-metatabs-options#2]
Hi,

I had problems using menuargs in the plugin to edit icon, position and capabilty. So I added the following to the code.

In the props array:
`'capability' => 'manage_options',
        'icon_url'   => 'dashicons-layout',
        'position'   => 1,`

And the build_menu_args-function:
`
private function build_menu_args ()  {

```
    // if a menu arguments array was injected, return it
    if ( ! empty( self::$props['menuargs'] ) ) {
        // if menu arguments are less than 7, add empty argument to end, assumes subpage wanted
        if ( count( self::$props['menuargs'] ) < 7 && self::$props['topmenu'] )
            self::$props['menuargs'][] = null;
        return self::$props['menuargs'];
    }

    // otherwise build the menu page from the page title and options-slug
    $args = array();
    if ( self::$props['topmenu'] ) {
        // add a post_type get var, to allow post options pages
        $add = self::$props['postslug'] ? '?post_type=' . self::$props['postslug'] : '';
        $args[] = self::$props['topmenu'] . $add;
    }
    $args[] = $args[] = self::$props['title'];
    $args[] = self::$props['capability'];
    $args[] = self::$props['key'];
    $args[] = array( $this, 'admin_page_display' );
    if ( ! self::$props['topmenu'] )
        $args[] = self::$props['icon_url'];
    $args[] = self::$props['position'];

    return $args;
}`
```

Would be a great and easier way to add those parameters

**Comment by rogerlos** [comment]
Yeah, my original method is fairly suspect. I think I'd prefer to keep the menu arguments organized under a single property, though...not that it probably matters. So something like:

``` php
$args['menuargs'] => array(
    'page_title' => '',
    'menu_title' => '',
    'capability' => '',
    'menu_slug' => '',
    'icon_url' => '',
    'position' => 20
);
```

With the understanding that any parameters left blank would default as they currently do.

**Comment by rogerlos** [comment]
Version 1.0.2 now addresses this with a revised and hopefully clearer argument building function.

``` php
$args['menuargs'] => array(
    'parent_slug' => '',
    'page_title' => '',
    'menu_title' => '',
    'capability' => 'manage_options',
    'menu_slug' => '',
    'icon_url' => '',
    'position' => null
);
```

Are the default arguments.

Within the menu builder, the following logic will apply to the `menuargs` values:

`parent_slug` will be filled from `self::$props['topmenu']` if that is set, or left empty for a new top menu.

`page_title` will be filled with `self::$props['title']` if empty.

`menu_title` will be filled with `self::$props['title']` if empty.

`capability` defaults as seen above.

`menu_slug` will be filled with `self::$props['key']` if empty.

`icon_url` will remain empty.

`position` will be null if empty.

**Comment by ajuliano** [comment]
I'm using this in a new project. Awesome! Thank you!
