### ISSUE TITLE
how tohow to echo field cmb2 with this plugin ? 

### ISSUE THREAD

**Issue by xyweb** [rogerlos/cmb2-metatabs-options#21]
Help me....
how to echo field 
i use cmb2_metatabs_options_go() but not working!!!!

example :  echo cmb2_metatabs_options_go( 'ex_cats_say' ); 

PLEASE help me and answer to my question....

**Comment by rubengc** [comment]
cmb2_metatabs_options_go() is a example function

Read again example.php to see how this plugin works

**Comment by xyweb** [comment]
I use example function but this class cmb2_metatabs_options_go() not working , and this plugin in my project is important ❤️ Please help

**Comment by rubengc** [comment]
You do not need to use cmb2_metatabs_options_go()

This method is called on cmb2 init hook

cmb2_metatabs_options_go() is like your_custom_function()

You need to make your own function that instantiates a new CMB2_Metatabs_Options

Or simply, copy the contents of example.php in your project and start to customize from here

**Comment by xyweb** [comment]
I copy example functions code in  my project and i edit forms and meta boxs , this options stored but i cant echo in my page or single post page not show , I dont know which function i called in echo !!!

**Comment by rubengc** [comment]
Check:
https://github.com/rogerlos/cmb2-metatabs-options/wiki/Arguments

Topmenu args define where your new menu will be show

Also, If you copied directly from example.php prefix each function call to avoid duplicates

**Comment by xyweb** [comment]
I create text type for example and this have id ,
You say use this id in ' ' ?
And echo code is --> echo get_options( 'text_id' );?

Excuse me im beginner in php code 😢🙏🏻

**Comment by xyweb** [comment]
Please type echo example for me 🙏🏻

**Comment by rubengc** [comment]
Ah, your fields are stored in an array of options

You need to use: 
$my_options = get_option( $your_options_prefix );
echo $my_options['text_id'];

**Comment by xyweb** [comment]
Tnx man ❤️ I love you

**Comment by rubengc** [comment]
Nothing ^^

**Comment by rubengc** [comment]
If you issue get solved, please close it

Thanks

**Comment by xyweb** [comment]
Yes its worked , Tnx
