### ISSUE TITLE
Everything was lost CMB2 plugin version 2.9

### ISSUE THREAD

**Issue by ozeron7** [rogerlos/cmb2-metatabs-options#28]
Everything was lost when I upgraded the CMB2 plugin to version 2.9. No problems in version 2.8.
Can you help fix this problem?
![ScreenHunter_3](https://user-images.githubusercontent.com/19690325/111318140-d2bf9a80-8675-11eb-88d1-7dff547e0714.jpg)
![ScreenHunter_4](https://user-images.githubusercontent.com/19690325/111318146-d3f0c780-8675-11eb-9536-de1737ee5bc2.jpg)

**Comment by rogerlos** [comment]
Hi, I haven't looked at this in a long while since CMB2 kind of went in a different direction. I'll see if I can take a peek later this week.

**Comment by rubengc** [comment]
Hi there! I was able to find and fix this issue on GamiPress and AutomatorWP (both using metatabs options)

CMB2 has added the value "10" for the box "priority" parameter as default for boxes rendered in options pages, causing this issue

Simply, register all your boxes with the "priority" to "high" to get all of them back

Hope it helps!

**Comment by ozeron7** [comment]
@rogerlos This plugin is very practical and useful. Thank you very much. Please don't leave it alone :)

@rubengc Thank you very much. The problem was solved by this method :)
