### ISSUE TITLE
Styling question

### ISSUE THREAD

**Issue by mralessio** [rogerlos/cmb2-metatabs-options#9]
Thank you for the plugin, it's very useful.
Is it possible to preserve a standard option page styling for the metaboxes ?
Like this:
![image](https://cloud.githubusercontent.com/assets/16015111/18485260/34d53f70-79fd-11e6-908e-3e442aea26ce.png)

**Comment by rogerlos** [comment]
CMO doesn't add any styles of its own except some cleanup when using tabs to better align some elements. You can set the `admincss` argument to `false` when calling CMO to remove those styles. 

What I think you are trying to do is remove the CMB2 stylesheet, which is done as shown on this page (link pulled from the CMB2 wiki): [Remove CMB2 styles on front end](http://kellenmace.com/disable-cmb2-styles-front-end-forms/).

You'd remove the `is_admin()` conditional from that example. Note, I have NOT tested this.
